In [10]:
print('Enter Your age')
age = input()
print(age) 



Enter Your age


 10


10


In [11]:
type(age)

str

In [12]:
Ama = int(age) + 20
print (Ama)

30


In [3]:
import numpy as np

In [4]:
1+1

2

In [5]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [6]:
Fa=np.array([[2,1,2], [3,5,6], [8,9,0]])
print(Fa)

[[2 1 2]
 [3 5 6]
 [8 9 0]]


In [7]:
Fa.ndim

2

In [8]:
Fa.shape

(3, 3)

In [9]:
Fa.dtype

dtype('int32')

In [10]:
a[1]

2

In [11]:
Fa[1]

array([3, 5, 6])

In [12]:
Fa[1]*2

array([ 6, 10, 12])

In [13]:
a[0], a[2]

(1, 3)

In [14]:
a[:3]

array([1, 2, 3])

In [15]:
print(a)

[1 2 3 4 5 6]


In [16]:
a[0:4]

array([1, 2, 3, 4])

In [17]:
Fa.shape

(3, 3)

In [18]:
a.shape

(6,)

In [19]:
Fa.shape, a.shape

((3, 3), (6,))

In [22]:
Fa.sum()

36

In [23]:
Fa.mean()

4.0

In [27]:
Fa.std()

2.9814239699997196

In [28]:
Fa.min()

0

In [29]:
Fa.max()

9